Black-Dot-2024/Zeitgeist-FrontEnd

src/App.tsx, src/colors.tsx, src/components/common/AddButton.tsx
Arregle el color incorrecto que tenia el boton en el commit original.
=> Diego perdomo s/componente add button y theme

src/App.tsx, src/pages/Clients/index.tsx, src/pages/Employees/index.tsx, src/pages/Home/index.tsx, src/pages/Projects/index.tsx, src/pages/Tasks/index.tsx
- Cambio en el orden de renderización de los elementos para que el layout no se re-renderice en cada cambio de pantalla.
=> fix(UI): Layout now does not re-render when changing pages

src/pages/Employees/index.tsx
[Feature/Task ID]: Eliminar empleado
Se realizó la base de la tabla de empleados
- se crea tabla empleados basica y estatica
- se añade boton de eliminar 
- se crea modal que solicita confirmación
23
front
Consultar empleado, consultar rol
Cualquier información adicional que el revisor o el autor del PR necesite saber. Aquí es donde se puede incluir imagenes, gifs, etc.
=> fix(index): employee index

src/pages/Projects/report.tsx
En esta refactorizacion, se ajusto el scroll de la vista de reporte para que el scroll solo fuera a la vista y no afecte el header ni la side bar
=> fix(page): scroll

src/pages/Projects/main.tsx
HotFix of UI Requests after API change.
=> fix(allProjects): fix requests after API change

src/pages/Projects/report-pdf.tsx
[RF21]: Consultar reporte proyecto
Ajustar el pdf para que se muestren 4 tareas por página
Se cambió el siguiente archivo:
- report-pdf.tsx
=> fix(frontend): 4 tasks per view (project report pdf)

src/components/modules/Employees/EmployeeeTable.tsx
[Feat/24]: Modificar rol de empleado
Se agregar los cambios necesarios al EmployeeTable para poder cambiar el rol de un empleado
- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.
2
El admin puede cambiar los roles de los empleados 
Para que esta funcione tienen que aceptar el pull request de feat/getAllRoles que esta en el backend.
https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/111
=> feat(employee): add update rol to employees handler

src/components/common/ClientCard.tsx
Modificaciones para seguir con el diseño de Figma
- Cambiar el color del nombre de cliente a dorado
- Poner el mismo tamaño de letra para el chip de legal hours.
=> Style Clientes

src/components/modules/Clients/EditClientFormModal.tsx
Se arregló el field de text residence
- Se arregló el acomodo de los fields del modal para asegurar que siempre estén alineados y que fuera lo más parecido al modal de crear cliente
Fetch de la fecha y el actualizar sin refresh
=> Style Edit Client

src/components/modules/Employees/EmployeeeTable.tsx
[Feature/Task ID]: RF50: fix scroll in email
Se quita el scroll en el mail
- change scroll in mail chip 
N/A
n/a
n//a
=> Fix(employee): fix scroll in email

src/components/common/CardProject.tsx, src/components/common/SideBar.tsx, src/components/modules/Employees/EmployeeeTable.tsx, src/pages/Projects/ProjectsClientList.tsx, src/pages/Projects/details.tsx
Se modificaron detalles de estilo para que se alinea más con el Figma 
Mejorar la usabilida
- Tamaño de chips de detalles de projecto
- Convertir las mayúsculas de LEGAL y ACCOUNTABLE a minúscula
- Hacer la side bar del marmol menos intensa lol 
- Poder acceder al detalle de un proyecto desde la vista de detalle de cliente
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/105307730/6ece57ca-8afd-4428-9411-81cbda6ad2ff
=> Style general

package.json, pnpm-lock.yaml, src/App.tsx, src/components/modules/Task/NewTask/NewTaskForm.tsx, src/pages/Projects/details.tsx, src/pages/Tasks/new.tsx, src/utils/constants.ts
Create task now works when clicking the new button in project details.
Checking with project details fetch tasks so that is refreshes when the view is reloaded
=> feat(createTask): create task working properly :)

src/components/modules/Clients/NewClientFormModal.tsx
[Fix]: Verificar que el phone number cumpla con los requisitos de longitud 
Agregar un verificador sobre el lenght el phone number que intenten registrar con el cliente 
- Agregar el if para verificar el length
1
Permite entre 8 a 15 números. (por si agregan lada)
Las imagenes deben coincidir con los prototipos de Figma
=> fix(number): Phone number length

src/components/common/GoBack.tsx, src/pages/Projects/report.tsx, src/pages/Tasks/task-detail.tsx
[Fix/RF20]: Arreglar defectos
Se abordan los siguientes issues:
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/115
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/116
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/117
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/121
Se modificaron/crearon los siguientes archivos:
- report.tsk
- GoBack.tsx
- task-detail.tsx
=> fix(frontend): styles

src/components/common/GenericDropdown.tsx
Updated for default value support
=> refactor(GenericDropdown): added new default value optional parameter

src/components/modules/Employees/EmployeeeTable.tsx
[Feature/Task ID]: Fix delete employee
No sale el botón de eliminar para el usuario que está en sesión, esto para que no te puedas eliminar a ti mismo y que siempre haya al menos un admin.
- EmployeeTable -> importar employeeContext
- EmployeeTable -> se añade una condición en el botón para que no aparezca si eres el usuario en sesión,
N/A
No poder borrarte a ti mismo
Enumera cualquier dependencia o PR relacionado que deba fusionarse antes o después de este PR.
=> fix(employee): now you cannot delete yourself

src/components/modules/Projects/ClientDropdown.tsx, src/components/modules/Projects/ProjectCard.tsx, src/pages/Projects/details.tsx, src/pages/Projects/edit.tsx, src/pages/Projects/main.tsx, src/types/project.ts
[Feature/Task ID]: RF59
Como usuario, quiero poder filtrar entre los proyectos archivados y no archivados.
- src/components/modules/Projects/ProjectCard.tsx
- src/pages/Projects/edit.tsx
- src/pages/Projects/main.tsx
- src/types/project.ts
3
[ ] En la vista de lista de proyectos (todos y los proyectos de cada cliente), el sistema muestra un filtro para poder observar ya sea los proyectos “archivados” o “no archivados”.
- RF58 Archivar Proyecto
=> feat(filter): filter archived projecs

src/types/project.ts
=> FIX: Quitar cliente de dropdown

src/pages/Projects/details.tsx
[Feature/Task ID]: Fix/RF01-Consultar-tareas
Arreglando overflow, función auxliar de formateo de fecha y margen de íconos.
- details.tsx
=> fix(fixingDetails): Fixing parser, padding and overflow

src/components/modules/Task/NewTask/NewTaskForm.tsx
Fixed TaskStatus enum parsing before posting to backend.
=> fix(createTask): fixed error in posting

src/components/modules/Task/TableTask/TaskTable.tsx
- Changed font color in due date in task table
- Fixed undefined label in worked hours when null
=> fix(assignedTasks): fixed font color in due date and undefined in hours

src/components/modules/Task/TaskListTable.tsx
Se agrego task detail a la vista de proyecto
=> fix(page): test detail

src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/pages/Tasks/update.tsx
[RF05]: Actualización de una tarea
Permite la actualización de los detalles de una tarea. Incluyendo:
- Título
- Descripción
- Start Date
- Due Date
- Status
- Assigned Employee
- Worked Hours
Permite la actualización de los detalles de una tarea
13
-  Título
-  Descripción
-  Fecha de inicio
-  Fecha de finalización
-  Persona encargada
-  Horas trabajadas
-  Estatus (Si el estatus cambia a “Done”, la fecha de finalización se actualiza al día que terminó la tarea)
-  Proyecto al que pertenece
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/2dda8eb3-c390-4663-b8e5-a77c08033fee
=> RF05: Update Task Styles

src/types/task-status.ts
[Issue 156]: Invalid task enums
Se arregló el siguiente [defecto](https://github.com/orgs/Black-Dot-2024/projects/7/views/1?pane=issue&itemId=62194346).
- Se actualizaron los enums del status de una task.
=> fix(enums): Fix task enums

src/components/modules/Employees/EmployeeeTable.tsx
[Fix/24]: Un usuario no puede cambiarse su propio rol
El usuario no es capaz de cambiarse.
-  EmployeeTable para bloquear al admin de cambiar su rol
=> Fix disabled update my user rol

src/components/modules/Task/NewTask/NewTaskForm.tsx
[Issue 162]: Visualización incorrecta de creación de una tarea
Se arregló el siguiente [defecto](https://github.com/orgs/Black-Dot-2024/projects/7/views/1?pane=issue&itemId=62202495).
- Se modificaron los estilos de la página de creación de una nueva tarea.
=> Fix: RF25 Style

src/components/modules/Task/TaskListTable.tsx, src/pages/Clients/index.tsx, src/pages/Projects/details.tsx, src/pages/Tasks/update.tsx, src/utils/methods.ts
[Feature/Task ID]: Show total worked hours from tasks
Sum all tasks worked hours to show total hours worked in project
- src/components/modules/Task/TaskListTable.tsx
1
[ ] La información que el usuario puede visualizar del proyecto incluye: Horas
NA
=> fix(hours): show worked hours in project details

pnpm-lock.yaml, src/components/common/GoBack.tsx, src/pages/Projects/details.tsx, src/pages/Projects/report.tsx, src/pages/Tasks/task-detail.tsx
[Refactor/RF04]: Cambio en el goBack
Se actualiza el goBack para ir a la última vista consultada.
Se cambiaron los siguientes archivos:
- GoBack.tsx
- details.tsx
- report.tsx
- task-detail.tsx
=> fix(frontend): goBack component

src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx
[RF62]: Consultar proyectos y clientes (Home Page)
Como usuario, quiero poder visualizar en la pantalla de inicio los proyectos y los clientes en donde estoy involucrado, (proyectos donde tengo tareas asignadas y clientes donde tengo proyectos con tareas asignadas)
- Se actualiza `src/pages/Clients/ClientDetails/ClientDetails`
- Se actualiza `src/pages/Clients/index.tsx`
Estos cambios permiten que se pueda acceder a la información del cliente desde esta vista y cualquier otro lugar (no solo desde la pestaña 'Clients' de la sidebar)
=> fix(RF62): Updated '/clients/:id' to be accessible globally

src/components/common/Header.tsx
- Usar el contexto de employee para renderizar la imagen de google
=> Render imagen de perfil

src/components/common/Layout.tsx, src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx
- Add back button
- Comment delete button as functionality is not implemented
=> fix(company): add back button and remove delete button

pnpm-lock.yaml, src/pages/Home/index.tsx
[Fix/RF62]: Fix Console Warnings in Homepage
Se agrega un atributo Key, para cada card de Clientes y así no se loguee un warning de React en la consola
- Se modifica ` src/pages/Home/index.tsx`
\-
\-
Ninguna
\-
=> fix(RF62): Added 'key' to company card to solve console warnings

src/pages/Home/index.tsx
[Fix/RF62]: Mostrar detalles de clientes en Homepage
Corregir el Link a los detalles de los clientes
- Se actualiza `src/pages/Home/index.tsx`
\-
Ninguna
=> fix(RF62): Fixed broken links from ClientsDetails

src/components/modules/Task/TaskListTable.tsx, src/utils/constants.ts
[RF03]: Task status now PUTs to backend when updated
Se agregó la funcionalidad de actualización de estatus de tarea en la vista de detalle de proyectos.
- Se actualizó el componente TaskListTable
- Se hace una request tipo PUT usando axios con el estado actualizado
5
- Not started
- In process
- Under revision
- Delay
- Postponed
- Done
- Cancelled 
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/2721a234-d6e0-4b85-b653-5ef0ba1ed172
=> RF03: Update Task Status

src/pages/Tasks/task-detail.tsx
=> fix(taskDetail): removed 2 2 left behind

src/components/modules/Task/TaskListTable.tsx
[Fix/RF16]: Warning en consola: Project Details
Aparecen Warning en la Vista por no usar adecuadamente `<Table>` de MUI/Joy
- Se modifica `src/components/modules/Task/TaskListTable`
\-
Ninguna
=> Fix/RF16: Warning en consola: Project Details

src/App.tsx, src/components/common/Layout.tsx, src/pages/Projects/details.tsx
Al crear tarea una tarea, el titulo muestra New Task en vez de Task Details
- layout.tsx
- app.tsx
- Project/details.tsx
Las imagenes deben coincidir con los prototipos de Figma
=> fix(layout): added New Task when creating a task

src/components/modules/Task/NewTask/NewTaskForm.tsx
El campo de worked hours es opcional al momento de crear una tarea
=> fix(createTask): worked hours is optional when creating a task

src/hooks/useNewProject.ts, src/pages/Projects/new.tsx
Se cambió la función de validación para que se valide la longitud de los inputs.
=> Agreagar validación extra al crear un proyecto

src/App.tsx, src/components/common/OfflineModal.tsx
=> feat(modal): no internet modal

src/pages/Projects/new.tsx
Add maxlines to textarea so you cannot overflow the content
=> fix(newProject): add maxline to textarea

index.html
Se agrego el favicon y un nombre al sitio
Defecto resuelto: https://github.com/orgs/Black-Dot-2024/projects/7/views/1?pane=issue&itemId=62369190
index.html
=> feat(page): favicon

src/pages/Clients/ClientDetails/ClientDetails.tsx
=> feat(clientDetails): add label to constitution date

src/components/modules/Projects/ProjectCard.tsx, src/pages/Projects/details.tsx, src/types/project.ts
Fixed warning from project status '-'
=> fix(projectStatus): fixed - warning

src/components/common/ClientCard.tsx, src/components/modules/Home/ClientCard.tsx, src/components/modules/Projects/ProjectCard.tsx, src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx, src/pages/Projects/details.tsx, src/utils/methods.ts
=> fix(text): truncate titles and names when length > 50

src/components/modules/Task/NewTask/NewTaskForm.tsx
Changed due date to end date in create task
=> fix(typo): fixed typo

src/components/common/GenericDropdown.tsx
El ícono del dropdown abre el menu y lo cierra.
=> refactor(GenericDropdown): fixed arrow icon not opening the menu

src/pages/Projects/report.tsx
[Fix/RF28]: Project report
Se cambia el width de los filtros
Se cambió el siguiente archivo:
- report.tsx
=> fix(frontend): dropdown width

src/components/common/SearchBar.tsx, src/components/modules/Employees/EmployeeeTable.tsx, src/pages/Employees/index.tsx
[Scre.io screen capture.webm](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/3bb8a0d1-58b7-45fc-9017-41cfe4650d61)
=> feat(employes): search bar component and search in employees

src/components/common/ArchiveModal.tsx, src/pages/Clients/ClientDetails/ClientDetails.tsx
[Fix/RF56]: Archivar clientes correctamente
El sistema ya archiva/desarchiva exitosamente y redirecciona a la página 'Clients'
- Se modifica `src/components/common/ArchiveModal`
- Se modifica `src/pages/Clients/ClientDetails/ClientDetails`
\-
Ninguna
=> fix(RF56): Archive/Unarchive now redirects properly to 'Clients' page

src/pages/Projects/report.tsx
[Fix/20]: Redirect
Se corrigieron ls mensajes de error y se redirige al usuario si no tiene acceso al reporte
project-report.tsx
=> fix(page): redirect

src/components/common/ClientCard.tsx, src/components/modules/Home/ClientCard.tsx, src/components/modules/Projects/ProjectCard.tsx
[Fix/RF27]: Fix Cards responsiveness for extreme cases/weird screen resolution
closes #296
- Se modifica `src/components/common/ClientCard`
- Se modifica `src/components/modules/Home/ClientCard`
- Se modifica `src/components/modules/Projects/ProjectCard.tsx`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/bec0c388-c756-459a-b85c-b8d0e9b444a0
=> fix(RF27): Responsive Cards for Projects & Clients

src/components/common/ArchiveModal.tsx, src/pages/Clients/ClientDetails/ClientDetails.tsx
[Fix/RF56]: Archive modal - Alert color&icon
closes #313 
- Se modifica `src/components/common/ArchiveModal`
- Se modifica `src/pages/Clients/ClientDetails/ClientDetails`
\-
Ninguna
=> fix(RF56): ArchiveModal Alert Color/Icon

src/components/modules/Projects/ClientDropdown.tsx, src/hooks/useNewProject.ts, src/pages/Projects/edit.tsx, src/types/project.ts
[Feature/Task ID]: Descripción del cambio
Arreglar defectos relacionados a los issues asociados a este PR
- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.
=> fix(RF15): validate fields while editing project

src/components/common/Header.tsx
[Feature/Task ID]: Descripción del cambio
Poner la fecha antes que el título
- src/components/common/Header.tsx
=> fix(header): place date before title

src/pages/Projects/edit.tsx
[Fix/RF15]: Update Navigate link when Update/Cancel project details
closes: #309
closes: #311 
- Se modifica ``
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/a6a75090-48f4-444c-925e-5c92cb9ed140
=> fix(RF15): Update Navigate link when Update/Cancel project details

src/components/modules/Task/NewTask/TableTask/TaskTable.tsx, src/pages/Tasks/assigned.tsx
La tipografía de la vista tiene un nuevo tamaño
=> refactor(assigned): increased font size

src/pages/Home/index.tsx
[Fix/RF62]: Clients -> My Clients
closes #318 
- Se modifica `/src/pages/Home/index.tsx`
\-
Ninguna
=> fix(RF62): Change 'Clients to 'My Clients'

src/pages/Projects/details.tsx, src/pages/Projects/edit.tsx
[Fix/RF16]: Retroalimentación del usuario
Al editar es estatus desde detalle de proyecto, se despliega un mensaje si el cambio fue exitoso
Se cambió el siguiente archivo:
- details.tsx
=> feat(frontend): message for project status change

src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Tasks/task-detail.tsx
[Fix/RF62]: Add responsiveness to 'Task Detail'
closes #377
- Se modifica `src/pages/Tasks/task-detail`
- Se borra código comentado en `src/pages/Clients/ClientDetails/ClientDetails`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/40b7a98e-c916-4b29-a6c6-444a70961119
=> fix(RF62): Task Detail Responsiveness

src/components/modules/Task/NewTask/NewTaskForm.tsx
[Fix/RF25]: Add Scroll to Description field in 'New Task'
closes #370
- Se modifica `src/components/modules/Task/NewTask/NewTaskForm`
\-
Ninguna
=> fix(RF25): Description Scroll

src/pages/Projects/details.tsx, src/pages/Tasks/assigned.tsx
[Fix/RF25]: Notify if task was deleted successfully
closes #388 
- Se modifica `src/pages/Projects/details`
- Se modifica `src/pages/Tasks/assigned`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/9c1f558a-afb8-4740-8716-68e881059351
ina
=> fix(RF25): Add notify to user when task deletes successfully

src/components/modules/Task/NewTask/NewTaskForm.tsx, src/pages/Tasks/task-detail.tsx
Se previene que el modal de crear tarea envie un 'workedhours' indefinido
- closes #394 
- Se modifica `src/components/modules/Task/NewTask/NewTaskForm
- Se modifica `src/pages/Tasks/task-detail``
=> fix(RF25): Add workedhours validation to prevent 'undefined'

src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Se valida la fecha de creación y finallización de una task para que se pueda crear el mismo dia
- closes #399 
- closes #371 
- Se modifica `src/components/modules/Task/NewTask/NewTaskForm`
- Se modifica `src/components/modules/Task/UpdateTask/UpdateTaskForm`
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/ea421639-7c2b-45e3-beb5-36cac2424a25
=> fix(RF05): Updated Datevalidators for start & due date

src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx, src/pages/Projects/details.tsx, src/pages/Projects/main.tsx, src/pages/Tasks/task-detail.tsx
Adding tooltips to icons + a few minor ui changes
- closes #325 
- src/pages/Clients/ClientDetails/ClientDetails.tsx
- src/pages/Clients/index.tsx
- src/pages/Projects/main.tsx
- src/pages/Tasks/task-detail.tsx
=> Adding tooltips to icons

src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx
Se valida el rol de usuario. Si es 'admin', muestra botones de filtrar, archivar/desarchivar
- closes: #256 
- closes: #257 
- closes: #292 
- closes: #293
- Se modifica `src/pages/Clients/ClientDetails/ClientDetails`
- Se modifica `src/pages/Clients/index`
=> fix(RF27RF57): ArchiveClients RBAC

src/pages/Projects/main.tsx
En este PR se modifica el estilo del filtro pro archivado en proyecto.
Resuelve el issue: https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/409
=> fix(page): filter

src/pages/Clients/ClientDetails/ClientDetails.tsx
[Fix/RF25]: Change button acording to attrib
- closes: #420
- Se modifica `src/pages/Clients/ClientDetails/ClientDetails.tsx`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/6e769e11-5b92-462e-b288-879fc947f420
=> fix(RF56): Archive/Unarchive button depends on archive attrib

src/pages/Tasks/task-detail.tsx
Se arregla la vista en caso de que 'due date' sea indefinida.
Cierra el defecto: https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/424
=> fix(page): due date

src/App.tsx, src/components/common/Layout.tsx, src/components/common/SideBar.tsx, src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx, src/pages/Projects/details.tsx, src/pages/Projects/index.tsx, src/pages/Tasks/index.tsx, src/pages/Tasks/task-detail.tsx
Al intentar entrar a una sub-ruta que no existe o al intentar buscar un proyecto, tarea o cliente que no existe, te redirecciona al 404.
- closes #241 
- closes #426
- closes #427
- closes #428   
- Todos los subrouters ahora incluyen un 404
- Se hace un check para el error 404 (revisar en backend, ya que si es un 404 se manda como 500)
- Refactor de como se determina el current item.
- Responsividad de proyectos
=> Not Found funcionalidades nuevas

src/pages/Clients/ClientDetails/ClientDetails.tsx, src/pages/Clients/index.tsx
Al filtrar cliente ya se ve la cosa de dani cuando no tiene en ese filtro
- closes #386 
- Solamente los cambios necesarios para que salga esa alerta
- Uno extra para que el boton de unarchive diga unarchive en lugar de archive
=> Clientes-RF57-6/7: Filtrar cliente

src/components/modules/Clients/NewClientFormModal.tsx
Corregir "constitucion" a "constitution" en modal de crear cliente
=> fix(client): modal constitution

src/pages/Projects/main.tsx
Se retroalimenta al usuario si el filtro no arroja resultados
- closes #401 
- closes #402 
Se cambió el siguiente archivo:
- main.tsx (projects)
Filtro: ARCHIVADOS
[Screencast from 12-05-24 20:48:13.webm](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91426086/a7dc36fc-78d5-4d1d-a80b-5c4f11758830)
=> fix(frontend): filtered projects not found

src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Los campos de fecha se validan si el usuario elimina con SUPR o DEL algún campo de la fecha (DD/MM/YYYY). El botón se desactiva si algún campo fue eliminado y se muestra un error de fecha inválida en la snackbar.
- closes #405
- Se modificó el archivo ```src/components/modules/Task/NewTask/NewTaskForm.tsx```
- Se modificó el archivo ```src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx``
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/b9d4af9e-776a-47bf-911c-385319901b0e
=> RF25: Dates are now validated when deleting DD or MM or YYYY on create task and update task.

src/components/common/ArchiveModal.tsx, src/pages/Clients/details.tsx
Refetching when a client is archived.
- closes #323 
- src/components/common/ArchiveModal.tsx
- src/pages/Clients/details.tsx
=> fix-RF56: Refetch

src/pages/Clients/main.tsx
[Fix/RF27]: Loader not displaying properly in Clients page
Se corrige la posición del loader en la página.
- Se modifica `src/pages/Clients/main`
\-
Ninguna
=> fix(RF27): Loader not displaying properly

src/components/common/CustomSelect.tsx, src/components/common/GoBack.tsx, src/components/modules/Projects/ClientDropdown.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/hooks/useNewProject.ts, src/pages/Projects/details.tsx, src/pages/Projects/edit.tsx, src/pages/Projects/new.tsx, src/pages/Tasks/details.tsx
Go Back va hacia atrás y evita páginas de creación y edición
- closes #392 
- Refactorización de creación y edición de proyectos
- Refactorización de creación y edición de tareas
- Refactorización de botón Go Back
=> MOD-RF00-ID00: Go Back button

src/components/modules/Clients/CreateClientButton.tsx, src/components/modules/Clients/EditClientButton.tsx, src/components/modules/Clients/EditClientFormModal.tsx, src/components/modules/Clients/NewClientFormModal.tsx, src/pages/Auth/index.tsx
Se agregaron validadores a todos los campos de creación y actualización de cliente. El botón de crear y actualizar cliente ahora se desactiva si alguno de los campos no cumple su validación. Se añadió un mejor mensaje de error cuando existe una falla en el sign in.
- closes #434 
- closes #300 
- closes #301 
- Se modificó el archivo ```src/components/modules/Clients/EditClientFormModal.tsx```
- Se modificó el archivo ```src/components/modules/Clients/NewClientFormModal.tsx```
- Se modificó el archivo ```src/components/modules/Clients/CreateClientButton.tsx```
- Se modificó el archivo ```src/components/modules/Clients/EditClientButton.tsx```
- Se modificó el archivo ```src/pages/Auth/index.tsx```
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/dbf3ca38-b932-4297-9e54-3 …
=> RF18-19: Clients fields validators

src/components/common/ClientCard.tsx, src/components/common/GenericDropdown.tsx, src/components/common/Header.tsx, src/components/common/Layout.tsx, src/components/common/SideBar.tsx, src/components/modules/Employees/EmployeeeTable.tsx, src/pages/Clients/details.tsx, src/pages/Clients/main.tsx, src/pages/Employees/index.tsx, src/pages/Home/index.tsx, src/pages/Projects/main.tsx
[Refactor/MainViews]: Added responsiveness in main views of the app
Se atiende el siguiente issue:
- closes: #472 
- Se modifica `src/components/common/ClientCard.tsx`
- Se modifica `src/components/common/GenericDropdown.tsx`
- Se modifica `src/components/common/Header.tsx`
- Se modifica `src/components/common/Layout.tsx`
- Se modifica `src/components/common/SideBar.tsx`
- Se modifica `src/components/modules/Employees/EmployeeeTable.tsx`
- Se modifica `src/pages/Clients/details.tsx`
- Se modifica `src/pages/Clients/main.tsx`
- Se modifica `src/pages/Employees/index.tsx`
- Se modifica `src/pages/Home/index.tsx`
- Se modifica `src/pages/Projects/main.tsx`
\-
Ver: https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/472
Ninguna. …
=> Refactor/Responsiveness v1.0

src/components/common/CustomSelect.tsx, src/pages/Projects/details.tsx, src/pages/Projects/edit.tsx, src/pages/Projects/new.tsx
Descripción concisa de los defectos solucionados.
- closes #466 
- Se agregó el contexto en crear proyecto
=> Proj/RF12/ID:6 y 14/No puedes crear proyectos para otra area

src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/pages/Tasks/details.tsx, src/pages/Tasks/edit.tsx, src/pages/Tasks/new.tsx
La snackbar verde se muestra solo si el estado de respuesta es 200
- closes #382 
Se movió la lógica de request al form y ahora se retroalimenta de manera correcta.
=> Tareas-RF25: Corregir botones de envío / fallo creación y actualización de tarea

package.json, pnpm-lock.yaml, src/components/common/NotFound.tsx
Cambie la libreria para que pueda funcionar con vercel
Muestra que los cambios realizados funcionen de la manera esperada.
=> fix(lottie): change library

src/components/modules/Clients/EditClientFormModal.tsx, src/pages/Clients/details.tsx
Poder enviar una fecha nula
- https://github.com/orgs/Black-Dot-2024/projects/7/views/1?pane=issue&itemId=62816707
- Usar `No date` para cuando no haya una fecha
- Poder enviar una fecha nula
[Screen Recorder (1).webm](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/875149fd-bf68-4dd7-b02a-4e0048d5847a)
=> fix(date): fix date in client

src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Se retira codigo residual de la snackbar (arregla la vista)
- closes: #485 
- Se modifica `src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx`
=> fix(RF05): Snackbar residual code

src/components/common/ColorChip.tsx, src/pages/Projects/report.tsx
[Refactor/MainViews]: Added responsiveness in project report view. All views are responsive. Except for login page & Sidebar/Hamburger
Se atiende el siguiente issue:
- closes: #493
- Se modifica `src/components/common/ColorChip.tsx`
- Se modifica `src/pages/Projects/report.tsx`
\-
Ver: https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/493
Ninguna.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/7b31d7a7-9d51-4a8b-864d-764de6216cdb
=> Refactor/Responsiveness v3.0

src/components/common/DeleteModal.tsx, src/pages/Tasks/details.tsx
Cuando eliminas una tarea, tira un error acerca de eliminar empleado
- closes #499
- 
- Se modifica `src/components/common/DeleteModal.tsx`
- Se modifica `src/pages/Tasks/details.tsx`
=> fix(RF26): Console Error: Trying to delete employee on TaskDelete

src/components/common/Layout.tsx, src/components/modules/Clients/EditClientFormModal.tsx, src/components/modules/Clients/NewClientFormModal.tsx
Se corrigió la forma en la que se validan los campos de cliente en el backend.
- closes #491
- closes #492
- closes #487
- Se modificaron los modales de creación y edición de cliente.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/28c76228-44c7-4ac6-9871-24227356f464
=> Fix: Client fields are now validated correctly

src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Worked hours are now optional when updating a task
- closes #496
=> fix(RF05): Worked hours are now optional when updating a task

src/App.tsx, src/components/modules/Clients/EditClientFormModal.tsx, src/components/modules/Clients/NewClientFormModal.tsx, src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/pages/Projects/edit.tsx, src/pages/Projects/new.tsx
Fix: All dates now use UTC-6 time zone
- closes #435
=> Fix: All dates now use UTC-6 time zone

src/pages/Clients/main.tsx, src/pages/Projects/main.tsx
- Filtro solo aparece si eres admin
- El filtro default es no archivados
=> Fix de Filtros

src/App.tsx, src/components/common/GenericDropdown.tsx, src/components/modules/Clients/EditClientFormModal.tsx, src/components/modules/Clients/NewClientFormModal.tsx, src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/NewTask/TableTask/TaskRow.tsx, src/components/modules/Task/NewTask/TableTask/TaskTable.tsx, src/components/modules/Task/TaskListTable.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/lib/dayjs/dayjs.ts, src/pages/Clients/details.tsx, src/pages/Projects/details.tsx, src/pages/Projects/edit.tsx, src/pages/Projects/new.tsx, src/pages/Tasks/main.tsx, src/utils/methods.ts
=> Refactor del Date Parsing

src/components/modules/Employees/EmployeeeTable.tsx
- Ya se puede eliminar el empleado otra vez
=> fix(employeeTable): Delete the employee correctly again

src/components/modules/Employees/EmployeeeTable.tsx, src/components/modules/Task/NewTask/TableTask/TaskRow.tsx, src/pages/Projects/details.tsx, src/pages/Tasks/edit.tsx
Se agrego el 'ComponentPlaceholder' cuando no se encuentran empleados al usar el filtro
Cierra el issue:  https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/issues/526
=> fix(page): add placeholders

src/components/common/GenericInput.tsx, src/components/common/GenericTextArea.tsx, src/hooks/useProjectForm.ts, src/hooks/useTaskForm.ts, src/pages/Projects/ProjectsClientList.tsx, src/pages/Projects/edit.tsx, src/pages/Projects/new.tsx
Se corrigieron detalles en los formularios de proyectos.
- closes #559 
- closes #562 
- closes #560 
- Se agregaron valores máximos a los inputs.
- Se muestran de manera correcta los errores de descripción
- Se usa `trim` al validar y enviar los campos
=> Proyectos-RF12: Formulario de nuevo proyecto

src/components/common/Header.tsx, src/components/common/SideBar.tsx
[Feature/RF61]: Acceder al calendario de Google
Se agregó un botón en el header para que los usuarios puedan acceder a su calendario de Google al hacer clic en el botón
- src/components/common/Header.tsx
- src/components/common/SideBar.tsx
3
=> feat(addingCalendar): Adding button to access calendar

src/components/common/ModalEditConfirmation.tsx
Agregar el warning al modal de archivar y desarchivar
- closes #547 
- Se agrego el warning
=> fix(modal): added alert

src/pages/Expenses/details.tsx
[Fix/RF32]: Redirect on 403
\-
- Se modifica `src/pages/Expenses/details.tsxs`. Si un usuario que no es Admin o Contable intenta acceder a un reporte de expense, te redirige a no encontrado
\-
- closes: #607 
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/8c8cd3fa-570e-4a54-b0a0-92dab4ff4bda
=> fix(RF32): Redirect on 403

src/components/common/SideBar.tsx
Close sidebar after selecting option
=> fix(sidebar): hide sidebar after selecting option

src/components/modules/Expenses/ExpensesTable.tsx, src/pages/Expenses/details.tsx
Se considera un 'Limit case' para asegurar la responsividad de la vista
- closes: #626
- Se modifica `src/components/modules/Expenses/ExpensesTable.tsx`
- Se modifica `src/pages/Expenses/details.tsx`
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/0a344eec-09c6-4981-8b1a-f4dd461731dc
=> fix(RF32): Responsiveness

src/components/common/Layout.tsx
La Sidebar no cubría la altura completa de manera responsiva
=> fix(layout): fix sidebar filling full height

src/components/common/SideBar.tsx
logout now removes firebase login too 
- closes #639 
logout now removes firebase login too .
=> fix(logout): logout now removes firebase login too

src/components/common/Layout.tsx, src/components/common/SideBar.tsx, src/pages/Expenses/details.tsx, src/pages/Projects/report.tsx
Agregar responsividad a la vista de detalle de reporte
- closes #626 
- UI
=> fix(ui): add responsiveness

src/pages/Projects/details.tsx, src/pages/Projects/report.tsx
Cuando se cambia el status del proyecto en la vista de detalles de un proyecto, se actualiza la vista de reporte de proyecto si está abierta en una pestaña adicional
- closes #573 
- closes #issue2
- src/pages/Projects/report.tsx
=> fix(reports): reload report page when proyect status changes

src/components/modules/Expenses/ExpensesTable.tsx, src/pages/Expenses/details.tsx, src/pages/Expenses/report.tsx, src/pages/Projects/main.tsx
[RF34]: Descaergar reporte de viático
Añadir formato de reporte en un componente.
- Se añadió el Link de descarga en la vista de detalle de viático
- Se añadió el reporte de viático 
Estima la complejidad de la tarea en puntos de historia.
- Al ingresar al detalle de un reporte (RF32 ), el sistema muestra la opción de descargar reporte.
- Al seleccionar la opción, el sistema descarga en archivo PDF el reporte a la computadora del usuario.
=> [RF34]: Descargar reporte de viático

src/components/modules/Clients/ClientFormModal.tsx
Se modificó el límite de caracteres que se pueden introducir en el campo de email de un cliente.
- closes #675 
- Se modificó el archivo ```src/components/modules/Clients/ClientFormModal.tsx```
N/A
=> fix(RF19): Company email is now capped to 70 characters

src/pages/Projects/report-pdf.tsx
Se distribuye correctamente el espacio de las hojas de cada pdf
- closes #681 
- project-report-pdf.tsx
=> Fix project report pdf

src/components/common/ProtectedRoute.tsx
Si un usuario sin rol intenta ingresar a una vista protegida, el sistema lo redirige a la vista de inicio de sesión
- closes #680 
- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/0d0922d9-91d7-4764-9a08-6f81268daaf3
=> fix(auth): redirect user with no role to login

src/pages/Tasks/edit.tsx, src/pages/Tasks/new.tsx
Se modificó la lógica de filtros en el dropdown de employees al crear y editar una task.
- closes #685 
- Se modificó el archivo ´´´src/pages/Tasks/edit.tsx´´´
- Se modificó el archivo ´´´src/pages/Tasks/new.tsx´´´
Muestra que los cambios realizados funcionen de la manera esperada.
=> fix(RF25): Dropdown now shows admin employees when creating and updating a task

src/components/common/ProtectedRoute.tsx, src/pages/Auth/index.tsx
Si un usuario sin rol intenta ingresar al sistema, el sistema ya no guarda sus token en el almacenamiento local, por lo que no puede acceder al sistema.
Por lo tanto, cuando se recarga la página, ya no te redirige a la vista principal
Además, el botón de Google Login se deshabilita después de dar click sobre él
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/f019c5d8-a1ed-49ea-8113-8420a07edb82
=> fix(auth): do not set tokens for user with No Role role

src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/hooks/useTaskForm.ts, src/pages/Tasks/details.tsx
En los inputs con números, cuando se escribe un número, el cero se borra 
- Lista los cambios específicos realizados en este PR, incluidos cambios en archivos, nuevas funcionalidades, correcciones de errores, etc.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/a606f59a-3c47-4ed2-bc84-55524072a49a
=> fix(inputs): remove 0 after inputing numbers

src/components/common/GenericDropdown.tsx, src/components/modules/Clients/ClientFormModal.tsx, src/components/modules/Task/NewTask/NewTaskForm.tsx, src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx, src/hooks/useClientForm.ts, src/hooks/useProjectForm.ts, src/hooks/useTaskForm.ts, src/utils/constants.ts
Se validan los campos de fecha de manera estricta para:
- Crear proyecto
- Editar proyecto
- Crear tarea
- Editar tarea
- Crear cliente
- Editar cliente
**Se valida lo siguiente**:
- Se valida que la fecha de constitución de un cliente no sea menor al 31/12/1799
- Se valida que la fecha de inicio no sea menor al 01/01/2018
- Se valida que la fecha de fin no sea menor al 01/01/2018
- Se valida que la fecha de inicio no sea mayor a 10 años en adelante de la fecha actual
- Se valida que la fecha de fin no sea mayor a 10 años en adelante de la fecha actual
- Se valida que la fecha de fin sea mayor a la fecha de inicio
- Se valida que la fecha de inicio sea válida
- Se valida que la fecha de fin sea válida
- Se valida que la fecha de inicio de una tarea sea mayor a la fecha de inicio del …
=> fix(dates): validate dates

src/pages/Auth/index.tsx
Si existe un error al iniciar sesión, el botón de inicio de sesión se vuelve a habilitar
=> fix(auth): reset response if error

src/pages/Projects/details.tsx
=> fix(button): edit button

src/pages/Projects/details.tsx
Reverts Black-Dot-2024/Zeitgeist-FrontEnd#710
=> Revert "Develop to Staging"

src/components/modules/Task/NewTask/TableTask/TaskRow.tsx, src/pages/Projects/details.tsx, src/pages/Projects/main.tsx
Aumentar la altura del detalle del proyecto, cambiar isArchived por Archived, Payed por Paid y romper las frases por palabras y no letras
- src/components/modules/Task/NewTask/TableTask/TaskRow.tsx
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/b53b2564-94f4-4d34-999b-0d8362011694
=> fix(ui): improve user experience

src/components/common/SideBar.tsx, src/pages/Auth/index.tsx
Cambiar de Redirect a PopUp
Literal usé una versión anterior que ya teníamos que usa Pop Up
=> fix(Auth): redirect a pop up
