src/components/common/CardsGrid.tsx
src/components/common/Layout.tsx
src/components/modules/Projects/ProjectCard.tsx
src/pages/Clients/index.tsx
src/pages/Projects/index.tsx
src/pages/Projects/main.tsx
src/types/project.ts

[RF51]: Consultar todos los proyectos
Se creo la vista de consultar todos los proyectos.
- Se cambió el layout para que el overflow se haga de manera correcta
- Se creo el componente de cada card de proyecto 
- Se creó la vista de todos los proyectos
- Se realizó el fetch de los datos desde el backend.
7
Ninguna

RF51: Consultar todos los proyectos

---

src/components/modules/Projects/ProjectCard.tsx
src/types/project.ts

Arreglar el color de los chips.
- el color del status ya funciona.
- el color del chip de area legal y contable es el mismo
- se cambió a minúsculas el área
- no quise borrar client del enum de ProjectArea porque no se si afecte a algo.
-

Style Projects

---

src/components/modules/Clients/EditClientFormModal.tsx
src/pages/Clients/ClientDetails/ClientDetails.tsx

fix(ModifyClient): actualización automática sin necesidad de refresh
Se resolvió el problema de que no se actualizaba hasta que se hiciera un 
-Se añadió estado refetch en ClientDetails para actualizar los datos del cliente automáticamente tras cerrar el modal de edición.
- Implementación de método PUT en handleUpdate de EditClientFormModal para asegurar la actualización de datos del cliente.
- Propagación de setRefetch a EditClientFormModal para permitir la recarga de datos en ClientDetails sin necesidad de refresh manual.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/105307730/8eac8f63-1fe9-49c3-9515-672f4852ef48

fix(ModifyClient): actualización automática sin necesidad de refresh

---

src/components/common/ModifyButton.tsx
src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx

[Issue 159]: Botón cancelar en Update Task
[Issue 165]: Campos no validados en Update Task
Se arregló el defecto [159](https://github.com/orgs/Black-Dot-2024/projects/7/views/1?filterQuery=assignee%3A%40me&pane=issue&itemId=62200923) y el defecto [165](https://github.com/orgs/Black-Dot-2024/projects/7/views/1?filterQuery=assignee%3A%40me&pane=issue&itemId=62211235).
- Se agregó un navigate a tasks si se presiona el botón cancelar.
- Se modificó la lógica de validación de campos en el formulario.
- Se desactivó el botón de envío si los campos están vacíos.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/c7777570-d134-4260-af84-6ec6cdcbdd59

Fix: RF05 Bugs

---

src/pages/Projects/report-pdf.tsx
src/pages/Projects/report.tsx

[Fix/RF20]: Corregir Warnings
- Aparecen Warning en la Vista por no contar con un key={] en algunos elementos al mapear
- Se deben corregir las lineas con warning que aparecen en la consola
- Se modifica `src/pages/Projects/report-pdf`
- Se modifica ` src/pages/Projects/report`
\-
Ninguna

Fix/rf20  Vista Reporte Projecto

---

src/components/modules/Task/TableTask/TaskTable.tsx

[RF03]: Task status now PUTs to backend when updated on tasks page
Se agregó la funcionalidad de actualización de estatus de tarea en la vista de detalle de tareas.
- Se actualizó el componente TaskTable
- Se hace una request tipo PUT usando axios con el estado actualizado
5
- Not started
- In process
- Under revision
- Delay
- Postponed
- Done
- Cancelled

RF03: Status can now be updated on assigned tasks page

---

src/colors.tsx
src/components/common/GenericDropdown.tsx
src/components/modules/Task/NewTask/NewTaskForm.tsx
src/components/modules/Task/TableTask/TaskTable.tsx
src/components/modules/Task/TaskListTable.tsx
src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
src/pages/Projects/details.tsx

El componente ahora acepta colores para el fondo y texto de las opciones. Resolviendo el  [issue #186](https://github.com/orgs/Black-Dot-2024/projects/7/views/2?sliceBy%5Bvalue%5D=Nuevo&pane=issue&itemId=62288751).
- Estructura del componente generic dropdown 
- Tasks/new.tsx colorMap
- Tasks/assigned.tsx colorMap
- Task/TableTask/TaskTable.tsx colorMap
- UpdateTask/UpdateTaskForm.tsx colorMap
- TaskListTable.tsx colorMap
- Proyect/details.tsx colorMap
- Task/NewTask/TaskForm.tsx colorMap

refactor(GenericDropdownStyles): updated the generic dropdown styles

---

src/components/common/GenericDropdown.tsx

refactor(GenericDropdownStyles): new styles for dropdown

---

src/pages/Projects/report.tsx

[Fix/RF21]: Descargar un reporte pdf con extensión incorrecta
Si un proyecto tiene de nombre `<nombre>.<nombre>` el pdf se descarga con extensión incorrecta
- Se modifica `src/pages/Projects/report.tsx`
\-
\-
Ninguna

fix(RF21): Project with '.' downloads with wrong extension

---

src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
src/components/modules/Task/TaskListTable.tsx

[Fix/RF05]: Se corrige el Redirect a 'Edit Task'
Resolución del RF #329
- Se modifica `src/components/modules/Task/NewTask/TableTask/TaskTable`
- Se modifica `src/components/modules/Task/TaskListTable`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/8ed270f0-0ee0-4edd-880d-96e4b6359c0f

fix(RF05): Task Redirect onClick 'Edit'

---

src/pages/Clients/ClientDetails/ClientDetails.tsx
src/pages/Projects/main.tsx

[Fix/RF17]: ClientDeets Truncate too long names
Se arregla PR: closes #287
- Se modifica `src/pages/Clients/ClientDetails/ClientDetails`
- Se modifica `src/pages/Projects/main.tsx`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/945def99-9f15-4468-9184-25a40f23dd54

fix(RF17): ClientDeets Truncate too long names

---

src/components/modules/Task/NewTask/NewTaskForm.tsx
src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx

[Fix/RF25]: Specific messages for missing fields on Snackbar
closes: #333 
- Se modifica `src/components/modules/Task/NewTask/NewTaskForm`
- Se modifica `src/components/modules/Task/UpdateTask/UpdateTaskForm`
\-
Ninguna
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/91692094/6973ea40-98aa-4997-8d1a-727397c0ab1a

fix(RF25): Specific messages for missing fields on Snackbar

---

src/components/modules/Task/NewTask/NewTaskForm.tsx
src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
src/types/task.ts

Se corrigió el envío de endDate y employee al backend. El botón de crear y actualizar tarea ahora se desactiva cuando le haces click para evitar exploits. El botón se reactiva después de 3 segundos en caso de que no se haya posteado correctamente. Se modificó el schema de task para corregir este error.
- closes #419
- closes #373
- Se modificó el archivo ```src/components/modules/Task/NewTask/NewTaskForm.tsx```
- Se modificó el archivo ```src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx```
- Se modificó el archivo ```src/types/task.ts```
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/06360227-3d2f-44df-b404-e8fb8a4284a2

RF05-25: Tasks now POST correctly when employee or end date are null. Button now disables when it is posting to avoid exploits.

---

src/components/modules/Clients/NewClientFormModal.tsx

- Se modificó  el modal de nuevo cliente para que el validator de RFC se igual al validator de modal para modificar.
--- 
---- 
```
export const validRFC = (rfc: string): boolean => {
const regex = /^[a-zA-Z]{3,4}[0-9]{6}[a-zA-Z0-9]{3}$/;
return regex.test(rfc);
}; 
```

Unificar validator para RFC

---

src/pages/Projects/report.tsx

Se añade un mes por defecto al filtro de proyectos
- closes #551 
- Se añade un value dentro del Selector Month en `src/pages/Projects/report.tsx`

fix(RF20): Add 'January' as default month to the filter

---

src/pages/Projects/report.tsx

Se añade un mes por defecto al filtro de proyectos
- closes #551 
- Se añade un value dentro del Selector Month en `src/pages/Projects/report.tsx`

fix(RF20): Add 'January' as default month to the filter 

---

src/components/modules/Task/NewTask/TableTask/TaskRow.tsx
src/pages/Projects/details.tsx
src/pages/Projects/report-pdf.tsx
src/pages/Projects/report.tsx
src/pages/Tasks/edit.tsx

Estilos para que el texto no se salga de la pantalla del sistema o la hoja del pdf.
- closes #548 
Se modificaron los siguientes archivos:
- report.tsx
- report-pdf.tsx

fix(frontend): report and pdf text

---

src/components/common/SideBar.tsx

Había un error con el comportamiento de la transparencia con la sidebar y ya funciona con congruencia
Se cambió el **bg-black bg-opacity-50** de  un div al aside
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/105307730/91fd58a8-f3eb-4077-982d-64c09e8d73e7

fix(sidebar): transparency

---

src/pages/Expenses/details.tsx

La página no espera a la request del Backend si demora mucho y redirige al 404. Debe hacer esto solo si manda un Unauthorized o un Not found
- closes #619 
- Se modifica la lógica de la vista para el redirect

Fix/RF32 RedirectOn403

---

src/pages/Auth/index.tsx

Evitar que se pueda iniciar sesión múltiples veces.
- closes #662 
- se agregó un useState para verificar si ya se inició el proceso de iniciar sesión, si es verdad, entonces el botón se pone en disabled para evitar poder picarlo múltiples veces.
Se ve como por .2 segundos pero se ve 😃 
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/105307730/f82dc279-a55e-4147-9929-39b510b04d96

fix(auth): branch

---

src/pages/Projects/edit.tsx
src/pages/Projects/new.tsx

Se utiliza ahora un endpoint que devuelve únicamente los clientes que NO estén archivados al crear un proyecto.
- closes #677 
- Se modificó el archivo ```src/pages/Projects/edit.tsx```
- Se modificó el archivo ```src/pages/Projects/new.tsx```
N/A

fix(RF12): Dropdown now only shows unarchived companies

---

src/components/modules/Employees/EmployeeeTable.tsx
src/hooks/useDeleteEmployee.ts

Cuando se elimina un empleado, se vuelve a consultar todos los usuarios
Muestra que los cambios realizados funcionen de la manera esperada.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/0cc56c53-32c0-45e5-a7a8-cbaeae057910

fix(employees): refetch employees after delete

---

src/pages/Projects/details.tsx

Se utilizó un estado separado para abrir el modal de archivar y eliminar un proyecto
Muestra que los cambios realizados funcionen de la manera esperada.
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/71858836/ff091146-49d2-4c27-9b26-6704d73d6e85

fix(modal): add separate states for archive and delete modals
